<?php

/**
 * Implements hook_menu().
 */
function shrtr_menu() {
  $items['shrtr/new'] = array(
    'title' => 'New URL',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shrtr_new_form'),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Returns a form array for submit new ULR-s.
 */
function shrtr_new_form($form = array(), &$form_state) {
  $form['url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

/**
 * Form submit hook, insert new URLs to database.
 */
function shrtr_new_form_submit($form, &$form_state) {
  global $user;

  $record = array(
    'url' => $form_state['values']['url'],
    'uid' => $user->uid,
    'created' => REQUEST_TIME,
  );

  drupal_write_record('shrtr_urls', $record);
}
