<?php

/**
 * Implements hook_menu().
 */
function shrtr_menu() {
  $items['shrtr/new'] = array(
    'title' => 'New URL',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shrtr_new_form'),
    'access arguments' => array('access content'),

  );
  $items['shrtr/%'] = array(
    'title' => 'URL',
    'page callback' => 'shrtr_goto',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );
  $items['shrtr/list'] = array(
    'title' => 'URL list',
    'page callback' => 'shrtr_list_page',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Returns a form array for submit new ULR-s.
 */
function shrtr_new_form($form = array(), &$form_state) {
  $form['url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL'),
    '#size' => 30,
  );
  $form['expire'] = array(
    '#type' => 'select',
    '#title' => t('Expire'),
    '#options' => array(
      0 => t('Never'),
      600 => '10' . t('min'),
      1200 => '20' . t('min'),
    ),
    '#default_value' => 0,
    '#description' => t('Time to expire'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

/**
 * Form submit hook, insert new URLs to database.
 */
function shrtr_new_form_submit($form, &$form_state) {
  global $user;
  global $base_url;

  $record = array(
    'url' => $form_state['values']['url'],
    'uid' => $user->uid,
    'created' => REQUEST_TIME,
    'expire' => REQUEST_TIME + $form_state['values']['expire'],
  );

  drupal_write_record('shrtr_urls', $record);
}

/**
 * Redirects to long URL.
 */
function shrtr_goto($id) {
  $url = db_select('shrtr_urls', 's')
    ->fields('s', array('url'))
    ->condition('id', $id)
    ->execute()
    ->fetchAssoc();

  drupal_goto($url['url']);
}

function shrtr_block_info() {
  $blocks['shrtr_new'] = array(
    'info' => t('Submit new URL'),
  );
  return $blocks;
}

function shrtr_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'shrtr_new':
      $block['subject'] = t('New URL');
      $block['content'] = array(
        'form' => drupal_get_form('shrtr_new_form'),
      );
      break;


  }
  return $block;
}

function shrtr_list_page() {
  global $base_url;

  $urls = db_select('shrtr_urls', 's')
     ->fields('s')
     ->execute();

  $header = array(t('ID'), t('User'), t('Original URL'), t('New URL'), t('Subbmitted'), t('Expire time'));
  $rows = array();

  while ($url = $urls->fetchAssoc()) {
    $new_url = $base_url . '/shrtr/' . $url['id']; 
    $row = array();
    $row[] = $url['id'];
    $row[] = $url['uid'];
    $row[] = l($url['url'], $url['url']);
    $row[] = l($new_url, $new_url);
    $row[] = format_date($url['created']);
    $row[] = format_date($url['expire']);
    $rows[] = $row;
  }
  
  $content['table'] = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
  );

  return $content;
}
